import re

class HashExtractor:
    def __init__(self):
        pass

    def identify_hash_type(self, hash_str):
        # Linux Shadow prefixes
        if hash_str.startswith("$1$"): return "MD5 (Linux)"
        if hash_str.startswith("$2a$") or hash_str.startswith("$2y$"): return "Bcrypt"
        if hash_str.startswith("$5$"): return "SHA-256 (Linux)"
        if hash_str.startswith("$6$"): return "SHA-512 (Linux)"
        
        # Windows NTLM (32 hex chars)
        if re.match(r'^[0-9a-fA-F]{32}$', hash_str):
            return "NTLM (Windows)"
            
        return "Unknown"

    def parse_linux_shadow(self, file_content):
        """
        Parses content resembling /etc/shadow
        Format: username:$id$salt$encrypted:lastchange:min:max:warn:inactive:expire
        """
        results = []
        lines = file_content.split('\n')
        for line in lines:
            parts = line.split(':')
            if len(parts) >= 2:
                username = parts[0]
                full_hash = parts[1]
                
                # Skip locked accounts (* or !)
                if len(full_hash) < 5 or full_hash in ['*', '!']:
                    continue
                    
                algo = self.identify_hash_type(full_hash)
                results.append({
                    "username": username,
                    "hash": full_hash,
                    "algorithm": algo,
                    "source": "Linux Shadow"
                })
        return results

    def parse_windows_dump(self, file_content):
        """
        Parses content resembling pwdump/SAM output
        Format: User:RID:LM:NTLM:::
        """
        results = []
        lines = file_content.split('\n')
        for line in lines:
            parts = line.split(':')
            if len(parts) >= 4:
                username = parts[0]
                lm_hash = parts[2]
                ntlm_hash = parts[3]
                
                # Check for empty/dummy hashes
                # NO PASSWORD (32 0s) or EMPTY (31d6cfe0d16ae931b73c59d7e0c089c0)
                if ntlm_hash and len(ntlm_hash) == 32:
                    results.append({
                        "username": username,
                        "hash": ntlm_hash,
                        "algorithm": "NTLM",
                        "source": "Windows SAM"
                    })
        return results

    def parse_csv_dump(self, file_content):
        """
        Parses simple CSV dumps (like the ones generated by this tool's Hash Manager).
        Expected: Plain, Hash, Algo OR just Hash, Algo
        """
        results = []
        lines = file_content.split('\n')
        for line in lines:
            line = line.strip()
            if not line or "Hash_Value" in line: continue
            
            parts = line.split(',')
            # Format: ***, <hash>, <algo> (3 parts)
            if len(parts) >= 2:
                # If 3 parts, usually [User/Plain, Hash, Algo]
                # If parts[0] is '***' or plain, we treat it as unknown user or 'TestUser'
                h_val = parts[1].strip() if len(parts) >= 3 else parts[0].strip()
                algo = parts[2].strip() if len(parts) >= 3 else "Unknown"
                
                # Check if it looks like a hash (hex)
                if re.match(r'^[a-fA-F0-9]+$', h_val):
                    results.append({
                        "username": "TestUser",
                        "hash": h_val,
                        "algorithm": algo,
                        "source": "CSV Dump"
                    })
        return results
